
import Common.OpenPdf;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import dao.ConnectionProvider;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.table.TableModel;
import java.util.Calendar;
import java.util.Date;
import dao.PharmacyUtils;
import java.awt.event.ActionEvent;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JTable;
import org.w3c.dom.events.MouseEvent;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author KWAKU
 */
public class SellMedicine extends javax.swing.JFrame {

    public String numberPattern = "^[0-9]*$";
    private int finalTotalPrice = 0;
    private String billId = "";
    private String username = "";

    /**
     * Creates new form SellMedicine
     */
    public SellMedicine() {
        initComponents();
    }

    public SellMedicine(String tempUsername) {
        initComponents();
        username = tempUsername;
        setLocationRelativeTo(null);
    }

    private void MedicineName(String nameOrUniqueId) {
        DefaultTableModel model = (DefaultTableModel) medicinesTable.getModel();
        model.setRowCount(0);
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from medicine where name like '" + nameOrUniqueId + "%' or uniqueId like '" + nameOrUniqueId + "%' ");
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("uniqueId") + " - " + rs.getString("name")});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void clearMedicineFields() {
        txtUniqueId.setText("");
        txtName.setText("");
        txtCompanyName.setText("");
        txtPricePerUnit.setText("");
        txtNoOfUnits.setText("");
        txtTotalPrice.setText("");
    }

    public String getUniqueId(String prefix) {
        return prefix + System.nanoTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        medicinesTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtUniqueId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPricePerUnit = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNoOfUnits = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        btnAddToCart = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        lblFinalTotalPrice = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("Sell Medicine");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 82, 1354, 10));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1317, 15, 35, 35));

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("Search");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        txtSearch.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 387, 36));

        medicinesTable.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        medicinesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicines"
            }
        ));
        medicinesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medicinesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(medicinesTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 387, 539));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel3.setText("Medicine ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        txtUniqueId.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        getContentPane().add(txtUniqueId, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 245, 36));

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel4.setText("Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, -1));

        txtName.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 245, 36));

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel5.setText("Company Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        txtCompanyName.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        getContentPane().add(txtCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 245, 36));

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel6.setText("Price Per Unit:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, -1, -1));

        txtPricePerUnit.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        getContentPane().add(txtPricePerUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 110, 240, 36));

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel7.setText("No. of Units:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 190, -1, -1));

        txtNoOfUnits.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        txtNoOfUnits.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNoOfUnitsKeyReleased(evt);
            }
        });
        getContentPane().add(txtNoOfUnits, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 180, 240, 36));

        jLabel8.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel8.setText("Total Price:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 250, -1, -1));

        txtTotalPrice.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        getContentPane().add(txtTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 240, 240, 36));

        btnAddToCart.setBackground(new java.awt.Color(204, 255, 204));
        btnAddToCart.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        btnAddToCart.setForeground(new java.awt.Color(0, 102, 51));
        btnAddToCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add to cart.png"))); // NOI18N
        btnAddToCart.setText("Add to Cart");
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 639, 38));

        cartTable.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine ID", "Medicine Name", "Price Per Unit", "No. of Units", "Total Price"
            }
        ));
        cartTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(cartTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 766, 296));

        jLabel9.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 51));
        jLabel9.setText("GHc:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 680, -1, -1));

        lblFinalTotalPrice.setBackground(new java.awt.Color(204, 255, 204));
        lblFinalTotalPrice.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        lblFinalTotalPrice.setForeground(new java.awt.Color(0, 102, 51));
        lblFinalTotalPrice.setText("00");
        getContentPane().add(lblFinalTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 680, -1, -1));

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 51));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/generate bill & print.png"))); // NOI18N
        jButton3.setText("Purchase & Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 680, 179, 39));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sellMedicineBackground.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        MedicineName("");
        txtUniqueId.setEditable(false);
        txtName.setEditable(false);
        txtCompanyName.setEditable(false);
        txtPricePerUnit.setEditable(false);
        txtTotalPrice.setEditable(false);
    }//GEN-LAST:event_formComponentShown

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String search = txtSearch.getText();
        MedicineName(search);
    }//GEN-LAST:event_txtSearchKeyReleased

    public class MedicineTableHandler {

        private final Map<String, Medicine> medicineMap;
        private final List<Medicine> medicineList;
        private final JTable medicinesTable;

        public MedicineTableHandler(JTable medicinesTable) {
            this.medicineMap = new HashMap<>();
            this.medicineList = new ArrayList<>();
            this.medicinesTable = medicinesTable;
            loadMedicinesFromDatabase();
        }

        private void loadMedicinesFromDatabase() {
            try (Connection con = ConnectionProvider.getCon(); Statement st = con.createStatement(); ResultSet rs = st.executeQuery("SELECT * FROM medicine")) {

                while (rs.next()) {
                    String uniqueId = rs.getString("uniqueId");
                    Medicine medicine = new Medicine(
                            uniqueId,
                            rs.getString("name"),
                            rs.getString("companyName"),
                            rs.getString("price")
                    );
                    medicineMap.put(uniqueId, medicine);
                    medicineList.add(medicine);
                }
                updateTableModel();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

        private void updateTableModel() {
            DefaultTableModel model = new DefaultTableModel(
                    new Object[]{"Unique ID", "Name", "Company", "Price"}, 0
            );
            for (Medicine medicine : medicineList) {
                model.addRow(new Object[]{
                    medicine.getUniqueId(),
                    medicine.getName(),
                    medicine.getCompanyName(),
                    medicine.getPrice()
                });
            }
            medicinesTable.setModel(model);
        }

        public void handleMouseClick(MouseEvent evt) {
            int index = medicinesTable.getSelectedRow();
            if (index >= 0 && index < medicineList.size()) {
                Medicine medicine = medicineList.get(index);
                updateUIWithMedicineDetails(medicine);
            }
        }

        private void updateUIWithMedicineDetails(Medicine medicine) {
            txtUniqueId.setText(medicine.getUniqueId());
            txtName.setText(medicine.getName());
            txtCompanyName.setText(medicine.getCompanyName());
            txtPricePerUnit.setText(medicine.getPrice());
            txtNoOfUnits.setText("");
            txtTotalPrice.setText("");
        }

        // Inner class to represent a Medicine
        private static class Medicine {

            private final String uniqueId;
            private final String name;
            private final String companyName;
            private final String price;

            public Medicine(String uniqueId, String name, String companyName, String price) {
                this.uniqueId = uniqueId;
                this.name = name;
                this.companyName = companyName;
                this.price = price;
            }

            // Getters
            public String getUniqueId() {
                return uniqueId;
            }

            public String getName() {
                return name;
            }

            public String getCompanyName() {
                return companyName;
            }

            public String getPrice() {
                return price;
            }
        }
    }

    private void medicinesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicinesTableMouseClicked
        // TODO add your handling code here:
        int index = medicinesTable.getSelectedRow();
        TableModel model = medicinesTable.getModel();
        String nameOrUniqueId = model.getValueAt(index, 0).toString();

        String uniqueId[] = nameOrUniqueId.split("-", 0);
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from medicine where uniqueId=" + uniqueId[0] + "");
            while (rs.next()) {
                txtUniqueId.setText(uniqueId[0]);
                txtName.setText(rs.getString("name"));
                txtCompanyName.setText(rs.getString("companyName"));
                txtPricePerUnit.setText(rs.getString("price"));
                txtNoOfUnits.setText("");
                txtTotalPrice.setText("");

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_medicinesTableMouseClicked

    private void txtNoOfUnitsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoOfUnitsKeyReleased
        // TODO add your handling code here:
        String noOfUnits = txtNoOfUnits.getText().trim(); // Trim whitespace
        if (!noOfUnits.equals("")) {
            String price = txtPricePerUnit.getText().trim(); // Trim whitespace
            if (!noOfUnits.matches(numberPattern)) {
                JOptionPane.showMessageDialog(null, "Number of Units field is invalid");
            } else {
                try {
                    int totalPrice = Integer.parseInt(noOfUnits) * Integer.parseInt(price);
                    txtTotalPrice.setText(String.valueOf(totalPrice));
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Invalid number format");
                }
            }
        } else {
            txtTotalPrice.setText("");
        }
    }//GEN-LAST:event_txtNoOfUnitsKeyReleased

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        // TODO add your handling code here:
        String noOfUnits = txtNoOfUnits.getText();
        String uniqueId = txtUniqueId.getText();

        if (!noOfUnits.isEmpty() && !uniqueId.isEmpty()) {
            String name = txtName.getText();
            String companyName = txtCompanyName.getText();
            String pricePerUnit = txtPricePerUnit.getText();
            String totalPrice = txtTotalPrice.getText();
            int checkStock = 0;
            int checkMedicineAlreadyExistInCart = 0;

            try {
                Connection con = ConnectionProvider.getCon();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select * from medicine where uniqueId='" + uniqueId + "'");
                if (rs.next()) {
                    if (rs.getInt("quantity") >= Integer.parseInt(noOfUnits)) {
                        checkStock = 1;
                    } else {
                        JOptionPane.showMessageDialog(null, "Medicine is Out of Stock. Only " + rs.getInt("quantity") + " Left");
                    }
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }

            if (checkStock == 1) {
                DefaultTableModel dtm = (DefaultTableModel) cartTable.getModel();
                for (int i = 0; i < dtm.getRowCount(); i++) {
                    if (dtm.getValueAt(i, 0).toString().equals(uniqueId)) {
                        checkMedicineAlreadyExistInCart = 1;
                        JOptionPane.showMessageDialog(null, "Medicine already exists in cart");
                        break;
                    }
                }
                if (checkMedicineAlreadyExistInCart == 0) {
                    dtm.addRow(new Object[]{uniqueId, name, pricePerUnit, noOfUnits, totalPrice});
                    finalTotalPrice = finalTotalPrice + Integer.parseInt(totalPrice);
                    lblFinalTotalPrice.setText(String.valueOf(finalTotalPrice));
                    JOptionPane.showMessageDialog(null, "Added Successfully");
                    clearMedicineFields();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Number of Units and Medicine ID fields are required.");
        }
    }//GEN-LAST:event_btnAddToCartActionPerformed

    public class MedicineCartManager {
    private final Map<String, Medicine> medicineInventory = new HashMap<>();
    private final List<CartItem> cartItems = new ArrayList<>();
    private int finalTotalPrice = 0;

    private static class Medicine {
        final String uniqueId;
        final String name;
        final String companyName;
        final int pricePerUnit;
        int quantity;

        Medicine(String uniqueId, String name, String companyName, int pricePerUnit, int quantity) {
            this.uniqueId = uniqueId;
            this.name = name;
            this.companyName = companyName;
            this.pricePerUnit = pricePerUnit;
            this.quantity = quantity;
        }
    }

    private static class CartItem {
        final Medicine medicine;
        final int quantity;
        final int totalPrice;

        CartItem(Medicine medicine, int quantity) {
            this.medicine = medicine;
            this.quantity = quantity;
            this.totalPrice = medicine.pricePerUnit * quantity;
        }
    }

    private void loadMedicineInventory() {
        try (Connection con = ConnectionProvider.getCon();
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery("SELECT * FROM medicine")) {
            
            while (rs.next()) {
                String uniqueId = rs.getString("uniqueId");
                Medicine medicine = new Medicine(
                    uniqueId,
                    rs.getString("name"),
                    rs.getString("companyName"),
                    rs.getInt("price"),
                    rs.getInt("quantity")
                );
                medicineInventory.put(uniqueId, medicine);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error loading medicine inventory: " + e.getMessage());
        }
    }

    private void btnAddToCartActionPerformed(ActionEvent evt) {
        String noOfUnits = txtNoOfUnits.getText().trim();
        String uniqueId = txtUniqueId.getText().trim();

        if (noOfUnits.isEmpty() || uniqueId.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Number of Units and Medicine ID fields are required.");
            return;
        }

        int requestedQuantity;
        try {
            requestedQuantity = Integer.parseInt(noOfUnits);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid number of units.");
            return;
        }

        Medicine medicine = medicineInventory.get(uniqueId);
        if (medicine == null) {
            JOptionPane.showMessageDialog(null, "Medicine not found in inventory.");
            return;
        }

        if (medicine.quantity < requestedQuantity) {
            JOptionPane.showMessageDialog(null, "Medicine is Out of Stock. Only " + medicine.quantity + " Left");
            return;
        }

        if (isItemInCart(uniqueId)) {
            JOptionPane.showMessageDialog(null, "Medicine already exists in cart");
            return;
        }

        CartItem newItem = new CartItem(medicine, requestedQuantity);
        cartItems.add(newItem);
        updateCartTable();
        updateTotalPrice();
        updateMedicineInventory(medicine, requestedQuantity);
        clearMedicineFields();
        JOptionPane.showMessageDialog(null, "Added Successfully");
    }

    private boolean isItemInCart(String uniqueId) {
        return cartItems.stream().anyMatch(item -> item.medicine.uniqueId.equals(uniqueId));
    }

    private void updateCartTable() {
        DefaultTableModel dtm = (DefaultTableModel) cartTable.getModel();
        dtm.setRowCount(0); // Clear existing rows
        for (CartItem item : cartItems) {
            dtm.addRow(new Object[]{
                item.medicine.uniqueId,
                item.medicine.name,
                item.medicine.pricePerUnit,
                item.quantity,
                item.totalPrice
            });
        }
    }

    private void updateTotalPrice() {
        finalTotalPrice = cartItems.stream().mapToInt(item -> item.totalPrice).sum();
        lblFinalTotalPrice.setText(String.valueOf(finalTotalPrice));
    }

    private void updateMedicineInventory(Medicine medicine, int quantitySold) {
        medicine.quantity -= quantitySold;
        // You might want to update the database here as well
    }

    private void clearMedicineFields() {
        txtUniqueId.setText("");
        txtName.setText("");
        txtCompanyName.setText("");
        txtPricePerUnit.setText("");
        txtNoOfUnits.setText("");
        txtTotalPrice.setText("");
    }
}
    
    private void cartTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartTableMouseClicked
        // TODO add your handling code here:
        int index = cartTable.getSelectedRow();
        if (index != -1) {  // Check if a row is actually selected
            int a = JOptionPane.showConfirmDialog(null, "Do you want to remove this Medicine from Cart?", "Select", JOptionPane.YES_NO_OPTION);
            if (a == JOptionPane.YES_OPTION) {
                TableModel model = cartTable.getModel();
                String total = model.getValueAt(index, 4).toString();  // Assuming total price is in column 5 (index 4)
                try {
                    finalTotalPrice = finalTotalPrice - Integer.parseInt(total);
                    lblFinalTotalPrice.setText(String.valueOf(finalTotalPrice));
                    ((DefaultTableModel) cartTable.getModel()).removeRow(index);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Error parsing total price: " + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row to remove.");
        }
    }//GEN-LAST:event_cartTableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (finalTotalPrice != 0) {
            billId = getUniqueId("Bill-");

            DefaultTableModel dtm = (DefaultTableModel) cartTable.getModel();
            if (cartTable.getRowCount() != 0) {
                for (int i = 0; i < cartTable.getRowCount(); i++) {
                    try {
                        Connection con = ConnectionProvider.getCon();
                        PreparedStatement ps = con.prepareStatement("update medicine set quantity=quantity-? where uniqueId=?");
                        ps.setInt(1, Integer.parseInt(dtm.getValueAt(i, 3).toString().trim())); // No. of Units
                        ps.setString(2, dtm.getValueAt(i, 0).toString().trim()); // Medicine ID
                        ps.executeUpdate();
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, "Error updating quantity: " + e.getMessage());
                    }
                }
            }

            try {
                SimpleDateFormat myFormat = new SimpleDateFormat("dd-MM-yyyy");
                Calendar cal = Calendar.getInstance();
                Connection con = ConnectionProvider.getCon();
                PreparedStatement ps = con.prepareStatement("insert into bill(billId,billDate,totalPaid,generatedBy) values(?,?,?,?)");
                ps.setString(1, billId);
                ps.setString(2, myFormat.format(cal.getTime()));
                ps.setInt(3, finalTotalPrice);
                ps.setString(4, username);
                ps.executeUpdate();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
            for (int i = 0; i < cartTable.getRowCount(); i++) {
                for (int j = 0; j < cartTable.getColumnCount(); j++) {
                    System.out.print(cartTable.getValueAt(i, j) + " | ");
                }
                System.out.println();
            }

            //Create Bill document
            // Inside the jButton3ActionPerformed method, replace the existing PDF generation code with this:
            com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
            try {
                PdfWriter writer = PdfWriter.getInstance(doc, new FileOutputStream(PharmacyUtils.billPath + "" + billId + ".pdf"));
                doc.open();
                Paragraph pharmacyName = new Paragraph("                                                DAISY PHARMACY - OMANJOR,ACCRA\n");
                doc.add(pharmacyName);
                Paragraph hyphenLine = new Paragraph("----------------------------------------------------------------------------------------------------------------------------------");
                doc.add(hyphenLine);
                Paragraph details = new Paragraph("\tBILL ID: " + billId + "\n DATE: " + new Date() + "\n TOTAL PAID[Ghc]: " + finalTotalPrice);
                doc.add(details);
                doc.add(hyphenLine);
                PdfPTable tbl = new PdfPTable(5);
                tbl.setWidthPercentage(100);
                tbl.setSpacingBefore(10f);
                tbl.setSpacingAfter(10f);

                // Set column widths
                float[] columnWidths = {1.5f, 1.5f, 1.5f, 1.5f, 1f};
                tbl.setWidths(columnWidths);

                // Add table headers
                String[] headers = {"MEDICINE ID", "NAME", "PRICE PER UNIT", "QUANTITY", "SUB TOTAL PRICE"};
                for (String header : headers) {
                    PdfPCell cell = new PdfPCell(new Phrase(header, new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD)));
                    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                    cell.setPadding(5);
                    tbl.addCell(cell);
                }

                // Add data rows
                DefaultTableModel model = (DefaultTableModel) cartTable.getModel();
                System.out.println("Number of rows in cart: " + model.getRowCount());
                for (int i = 0; i < model.getRowCount(); i++) {
                    for (int j = 0; j < 5; j++) {
                        Object value = model.getValueAt(i, j);
                        String cellValue = value != null ? value.toString() : "";
                        System.out.println("Adding cell value: " + cellValue);
                        PdfPCell cell = new PdfPCell(new Phrase(cellValue, new Font(Font.FontFamily.HELVETICA, 9, Font.NORMAL)));
                        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                        cell.setPadding(5);
                        tbl.addCell(cell);
                    }
                }

                doc.add(tbl);
                doc.add(hyphenLine);
                Paragraph thanksMsg = new Paragraph("Thank you for your purchase. Please Visit again. We are open 24/7");
                doc.add(thanksMsg);

                // Ensure all content is written to the PDF
                doc.close();
                writer.close();

                System.out.println("PDF generated successfully: " + PharmacyUtils.billPath + "" + billId + ".pdf");

                OpenPdf.openById(String.valueOf(billId));
                // OPEN PDF
                OpenPdf.openById(String.valueOf(billId));
            } catch (DocumentException | FileNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Error generating PDF: " + e.getMessage());
            }

            doc.close();

        } else {
            JOptionPane.showMessageDialog(null, "Please add some Medicine to Cart");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SellMedicine().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JTable cartTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFinalTotalPrice;
    private javax.swing.JTable medicinesTable;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNoOfUnits;
    private javax.swing.JTextField txtPricePerUnit;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTotalPrice;
    private javax.swing.JTextField txtUniqueId;
    // End of variables declaration//GEN-END:variables
}
